# This is a basic workflow to help you get started with Actions

name: python application

# Controls when the workflow will run
# Allows you to run this workflow manually from the Actions tab

on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
            python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
      - name: Install requests
        run: |
          pip install requests
      - name: Test with pytest
        env: 
          PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
          SANDBOX_API_KEY: ${{ secrets.SANDBOX_API_KEY }}
        run: |
          pip install pytest
          pytest
