name: Python application

on: 
  workflow_dispatch:
    inputs: 
      testing_environment:
        description: 'Select s - sandbox / p - prod'
        required: true
        default: 's'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
    - name: Install requests
      run: |
        pip install requests
    - name: Test with pytest
      env: 
        PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
        SANDBOX_API_KEY: ${{ secrets.SANDBOX_API_KEY }}
        env_value: ${{ github.event.inputs.testing_environment }}
      run: |
        pip install pytest
        pytest test_main.py

