name: OTL
on: [workflow_dispatch]
jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
    - name: Install requests
      run: |
        pip install requests
    - name: Test with pytest
      env: 
        SANDBOX_CLIENT_ID: ${{ secrets.SANDBOX_CLIENT_ID }}      
        SANDBOX_API_KEY: ${{ secrets.SANDBOX_API_KEY }}
      run: |
        pip install pytest
        pytest test_otl.py --junitxml sample.xml
    - name: Upload Test Result
      if: always()
      uses: actions/upload-artifacts@v2
      with:
        name: Unit Test Results
        path: sample.xml
  publish-test-results:
   name: "Publish Unit Tests Results"
   needs: build
   runs-on: ubuntu-latest
   if: always()
   
   steps:
   - name: Download Artifacts
     uses: actions/download-artifact@v2
     with:
        path: artifacts

   - name: Publish Unit Test Results
     uses: EnricoMi/publish-unit-test-result-action@v1
     with:
        files: artifacts/sample.xml
      
